name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.4]
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help
      - name: Install deps
        working-directory: funny-endpoints
        run: poetry install
      - name: Test
        working-directory: funny-endpoints
        run: poetry run pytest
      - name: Build
        working-directory: funny-endpoints
        run: poetry build
      - uses: actions/upload-artifact@v2
        with:
          name: funny-${{ matrix.os }}-${{ matrix.python-version }}
          path: src/dist/
